import { Role } from '../app/role/role.entity';

export type RoleId =
  | 'dashboard'
  | 'dashboard.widgets'
  | 'dashboard.widgets.incompleteIncidents'
  | 'dashboard.widgets.trends'
  | 'dashboard.widgets.tasks'
  | 'incidents'
  | 'incidents.index'
  | 'incidents.index.all'
  | 'incidents.report'
  | 'incidents.report.monitor'
  | 'incidents.report.create'
  | 'incidents.report.editTitle'
  | 'incidents.report.lock'
  | 'incidents.report.delete'
  | 'incidents.report.conclusion'
  | 'incidents.report.guestData'
  | 'incidents.report.suggestions'
  | 'incidents.report.allTitlesOnMouseover'
  | 'incidents.report.allowNotificationSuppression'
  | 'incidents.report.defaultNotificationSuppression'
  | 'incidents.alarms'
  | 'incidents.watchlist'
  | 'incidents.imports'
  | 'incidents.imports.import'
  | 'incidents.imports.socialMediaSearch'
  | 'analysis'
  | 'analysis.incidents'
  | 'analysis.instantSheets'
  | 'users'
  | 'users.users'
  | 'users.users.index'
  | 'users.users.index.ownGroup'
  | 'users.users.create'
  | 'users.users.edit'
  | 'users.users.delete'
  | 'users.tasks'
  | 'users.tasks.create'
  | 'users.standby'
  | 'users.standby.create'
  | 'users.standby.edit'
  | 'users.standIn'
  | 'users.standIn.create'
  | 'users.standIn.edit'
  | 'locations'
  | 'locations.index'
  | 'locations.index.all'
  | 'locations.manage'
  | 'locations.manage.details'
  | 'locations.manage.create'
  | 'locations.manage.edit'
  | 'locations.manage.editAdvanced'
  | 'locations.manage.delete'
  | 'profile.show'
  | 'profile.settings'
  | 'profile.settings.password'
  | 'handbook'
  | 'admin'
  | 'admin.userGroups'
  | 'admin.userGroups.create'
  | 'admin.userGroups.edit'
  | 'admin.userGroups.delete'
  | 'admin.userGroups.toggleActive'
  | 'admin.scenarios'
  | 'admin.scenarios.create'
  | 'admin.scenarios.edit'
  | 'admin.scenarios.general'
  | 'admin.scenarios.notifications'
  | 'admin.scenarios.permissions'
  | 'admin.scenarios.forms'
  | 'admin.scenarios.tasks'
  | 'admin.scenarioCategories'
  | 'admin.scenarioCategories.create'
  | 'admin.scenarioCategories.edit'
  | 'admin.sources'
  | 'admin.instantSheets'
  | 'admin.instantSheets.create'
  | 'admin.instantSheets.delete'
  | 'admin.instantSheetElements'
  | 'admin.instantSheetElements.create'
  | 'admin.instantSheetElements.delete'
  | 'admin.forms'
  | 'admin.forms.create'
  | 'admin.forms.delete'
  | 'admin.reportSources'
  | 'admin.reportSources.create'
  | 'admin.reportSources.delete'
  | 'admin.categories'
  | 'admin.categories.edit'
  | 'admin.currencies'
  | 'admin.taskTemplates'
  | 'admin.taskTemplates.create'
  | 'admin.taskTemplates.edit'
  | 'admin.taskTemplates.delete'
  | 'admin.locationAttributes'
  | 'admin.locationAttributes.create'
  | 'admin.locationAttributes.delete'
  | 'admin.distributionCenters'
  | 'admin.distributionCenters.create'
  | 'admin.distributionCenters.delete'
  | 'admin.regions'
  | 'admin.regions.create'
  | 'admin.crisisManagement'
  | 'admin.crisisManagement.create'
  | 'admin.crisisManagement.edit'
  | 'admin.crisisManagement.delete'
  | 'admin.alarms'
  | 'admin.alarms.create'
  | 'admin.serviceProviders'
  | 'admin.serviceProviders.create'
  | 'admin.serviceProviders.edit'
  | 'admin.serviceProviders.delete'
  | 'admin.lists'
  | 'admin.lists.create'
  | 'admin.lists.edit'
  | 'admin.lists.delete'
  | 'admin.languages'
  | 'admin.notificationTemplates'
  | 'admin.notificationTemplates.create'
  | 'admin.settings'
  | 'admin.activities';

export interface RoleInterface {
  id: RoleId;
  iconName?: string;
  navKey?: string;
  navSegment?: number;
}

export type RoleIndex = {
  [key in RoleId]: Role;
};

export interface UserGroupRoleInterface {
  roleId: RoleId;
  userGroupId: string;
}

export interface UserRoleInterface {
  roleId: RoleId;
  userId: string;
}
